version: "3.5"

###################################################################################################
services:
###################################################################################################
  openbim_oneclickpe-backend:
    image: registry.certi.org.br/cpc-openbim/oneclickpe-backend:1.0
    restart: on-failure
    container_name: openbim_oneclickpe-backend
    depends_on:
      - openbim_oneclickpe-certikey-backend
    # environment:
      # - port=8000
    networks:
      - openbim_oneclickpe_backend-net

###################################################################################################
  openbim_oneclickpe-certikey-backend:
    image: registry.certi.org.br/cpc-openbim/certikey-backend:1.0
    restart: on-failure
    container_name: openbim_certikey-backend
    # environment:
      # - port=8000
    networks:
      - openbim_oneclickpe-certikey-backend-net
      - openbim_oneclickpe_backend-net

###################################################################################################
  openbim_oneclickpe_frontend:
    image: registry.certi.org.br/cpc-openbim/oneclickpe-front:1.0
    restart: on-failure
    container_name: openbim_oneclickpe-frontend
    ports:
      - "8080:80"
    networks:
      - openbim_oneclickpe-certikey-backend-net
      - openbim_camunda-net

###################################################################################################
  openbim_camunda:
    #image: camunda/camunda-bpm-platform:7.13.0
    image: camunda/camunda-bpm-platform
    restart: on-failure
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://openbim_postgres-camunda:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - WAIT_FOR=openbim_postgres-camunda:5432
      - WAIT_FOR_TIMEOUT:30
      - CAMUNDA_POSTGRES_PASSWORD=password
    container_name: openbim_camunda
    ports:
      - "8081:8080"
    networks:
      - openbim_camunda-net
      - openbim_camunda-database-net
    depends_on: 
      - openbim_postgres-camunda
####################################################
  openbim_postgres-camunda:
    image: postgres:10
    restart: on-failure
    volumes:
      - ./postgres_camunda_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    container_name: openbim_postgres-camunda
    # ports: 
      # - "5434:5432"
    networks:
      - openbim_camunda-database-net
###################################################################################################

networks:
  openbim_camunda-net:
    driver: bridge
  openbim_camunda-database-net:
    driver: bridge
  openbim_oneclickpe_backend-net:
    driver: bridge
  openbim_oneclickpe-certikey-backend-net:
    driver: bridge

volumes:
  postgres_camunda_data:
    driver: local
