version: "3.5"

x-environment:
  &dbconnection-environment
    CERTIIO: http://172.17.0.1:3012
    CERTIKEY: http://172.17.0.1:3010
    GATEWAY: http://sub.petrobras.biz:3010/oneclickpe/
    POSTGRES_DB: i4
    POSTGRES_USER: i4
    POSTGRES_PASSWORD: i4#12345
    POSTGRES_ADDRESS: 172.17.0.1
    POSTGRES_PORT: 5432


x-volumes:
  &volume-certiio
  - /var/www/storage:./volumes/certiio_storage

###################################################################################################
services:
###################################################################################################
#########################################################################
#BACKEND
#########################################################################
  openbim_oneclickpe-backend:
    image: registry.certi.org.br/cpc-openbim/oneclickpe-backend:latest
    # image: e5rq/repository:oneclickpe
    restart: on-failure
    container_name: openbim_oneclickpe-backend-container
    depends_on:
      - openbim_oneclickpe-certikey-backend
    ports:
      - 3011:3011
    # environment:
    #   # - CERTIIO=http://host.docker.internal:3012
    #   # - CERTIKEY=http://host.docker.internal:3010
    #   # - CERTIIO=http://openbim_oneclickpe-certiio
    #   # - CERTIKEY=http://openbim_oneclickpe-certikey-backend
    #   - CERTIIO=http://172.17.0.1:3012
    #   - CERTIKEY=http://172.17.0.1:3010
    #   - GATEWAY=http://sub.petrobras.biz:3010/oneclickpe/
    #   - POSTGRES_DB=i4
    #   - POSTGRES_USER=i4
    #   - POSTGRES_PASSWORD=i4#12345
    #   - POSTGRES_ADDRESS=172.17.0.1
    #   - POSTGRES_PORT=5432
    environment: *dbconnection-environment
    # estilo docker servidor sub antigo
    # networks:
    #   - openbim_oneclickpe-net
    # servidor sub com podman mudança do rodrigo
    networks:
      openbim_oneclickpe-net:
        aliases:
          - openbim_oneclickpe-backend

###################################################################################################
  openbim_oneclickpe-certikey-backend:
    image: registry.certi.org.br/cpc-openbim/certikey-backend
    # image: e5rq/repository:certikey
    restart: on-failure
    container_name: openbim_certikey-backend-container
    ports: 
      - 3010:3010
    # environment:
    #   - POSTGRES_DB=i4
    #   - POSTGRES_USER=i4
    #   - POSTGRES_PASSWORD=i4#12345
    #   - POSTGRES_ADDRESS=172.17.0.1
    #   - POSTGRES_PORT=5432
    environment: *dbconnection-environment
    # networks:
    #   - openbim_oneclickpe-net
    networks:
      openbim_oneclickpe-net:
        aliases:
          - openbim_oneclickpe-certikey-backend

###################################################################################################
  openbim_oneclickpe-certiio:
    image: registry.certi.org.br/cpc-openbim/certiio-backend
    # image: e5rq/repository:certiio
    restart: on-failure
    container_name: openbim_certiio-container
    ports: 
      - 3012:3012
    #mudança de declaração de volume pra podman
    # volumes:
    #   - ./volumes/certiio_storage:/var/www/storage
    volumes: *volume-certiio
    # environment:
    #   - POSTGRES_DB=i4
    #   - POSTGRES_USER=i4
    #   - POSTGRES_PASSWORD=i4#12345
    #   - POSTGRES_ADDRESS=172.17.0.1
    #   - POSTGRES_PORT=5432
    environment: *dbconnection-environment
    # networks:
    #   - openbim_oneclickpe-net
    networks:
      openbim_oneclickpe-net:
        aliases:
          - openbim_oneclickpe-certiio

####################################################
  # openbim_postgres-backend:
    # image: postgres:10
    # restart: on-failure
    # volumes:
      # - ./postgres_backend_data:/var/lib/postgresql/data
    # environment:
      # POSTGRES_PASSWORD: root
    # container_name: openbim_postgres-backend-container
    # ports: 
      # - "5432:5432"
    # networks:
      # - openbim_oneclickpe_backend-net
      # - openbim_oneclickpe-certikey-backend-net

###################################################################################################
#########################################################################
#FRONT
#########################################################################
  openbim_oneclickpe_frontend:
    image: registry.certi.org.br/cpc-openbim/oneclickpe-frontend
    # image: e5rq/repository:frontend
    restart: on-failure
    container_name: openbim_oneclickpe-frontend-container
    # environment:
      # apiURL: openbim_oneclickpe-certikey-backend/oneclickpe
    ports:
      - "8180:80"
    # networks:
    #   - openbim_oneclickpe-net
      # - openbim_camunda-net
    networks:
      openbim_oneclickpe-net:
        aliases:
          - openbim_oneclickpe_frontend

###################################################################################################
#########################################################################
#Pgadmin
#########################################################################
#  openbim_pgadmin:
#    container_name: openbim_pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=fna@certi.org.br
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    volumes:
#       - ./pgadmin:/var/lib/pgadmin
#    ports:
#      - 5050:80
#    #networks:
#      #- postgres
#    restart: unless-stopped

###################################################################################################
#########################################################################
#CAMUNDA
#########################################################################
  # openbim_camunda:
    # #image: camunda/camunda-bpm-platform:7.13.0
    # image: camunda/camunda-bpm-platform
    # restart: on-failure
    # environment:
      # - DB_DRIVER=org.postgresql.Driver
      # - DB_URL=jdbc:postgresql://openbim_postgres-camunda:5432/postgres
      # - DB_USERNAME=postgres
      # - DB_PASSWORD=password
      # - WAIT_FOR=openbim_postgres-camunda:5432
      # - WAIT_FOR_TIMEOUT:30
      # - CAMUNDA_POSTGRES_PASSWORD=password
    # container_name: openbim_camunda
    # ports:
      # - "8181:8080"
    # networks:
      # - openbim_camunda-net
      # - openbim_camunda-database-net
    # depends_on: 
      # - openbim_postgres-camunda
# ####################################################
  # openbim_postgres-camunda:
    # image: postgres:10
    # restart: on-failure
    # volumes:
      # - ./postgres_camunda_data:/var/lib/postgresql/data
    # environment:
      # POSTGRES_PASSWORD: password
    # container_name: openbim_postgres-camunda
    # # ports: 
      # # - "5434:5432"
    # networks:
      # - openbim_camunda-database-net
###################################################################################################

networks:
  # openbim_camunda-net:
  #   driver: bridge
  # openbim_camunda-database-net:
  #   driver: bridge
  openbim_oneclickpe-net:
    # retirado driver por causa do podman
    # driver: bridge

volumes:
  postgres_camunda_data:
    # retirado driver por causa do podman
    # driver: local
